export type WodEntry = {
  word: string
  pos: string        // part of speech
  pronunciation: string
  definition: string
  example: string
}

const WORDS: WodEntry[] = [
  { word: 'Audacious',     pos: 'adj', pronunciation: 'aw-DAY-shus',      definition: 'Showing a willingness to take bold risks; daring beyond what is conventional.',                   example: 'She set an audacious goal to build her business from zero to six figures in one year.' },
  { word: 'Tenacity',      pos: 'n',   pronunciation: 'teh-NAS-ih-tee',    definition: 'The quality of holding firm to a purpose and refusing to give up despite obstacles.',             example: 'His tenacity through setbacks is what separated him from everyone who quit.' },
  { word: 'Catalyst',      pos: 'n',   pronunciation: 'KAT-uh-list',       definition: 'A person or event that causes change or action to happen faster.',                                example: 'One honest conversation can be the catalyst that changes the entire direction of your life.' },
  { word: 'Equanimity',    pos: 'n',   pronunciation: 'ee-kwuh-NIM-ih-tee', definition: 'Mental calmness and composure, especially in difficult situations.',                             example: 'She handled every challenge with equanimity, never letting setbacks shake her focus.' },
  { word: 'Fortitude',     pos: 'n',   pronunciation: 'FOR-tih-tyood',     definition: 'Courage and strength in the face of adversity or pain.',                                          example: 'Building anything real requires fortitude — most people quit long before results appear.' },
  { word: 'Perspicacious', pos: 'adj', pronunciation: 'pur-spih-KAY-shus', definition: 'Having a ready insight; shrewd; able to read situations clearly.',                               example: 'A perspicacious leader sees problems before they become crises.' },
  { word: 'Indefatigable', pos: 'adj', pronunciation: 'in-dih-FAT-ih-guh-bul', definition: 'Persisting tirelessly; never yielding to fatigue.',                                          example: 'Her indefatigable work ethic was the reason she outpaced everyone around her.' },
  { word: 'Luminous',      pos: 'adj', pronunciation: 'LOO-mih-nus',       definition: 'Radiating light; bright and inspiring; full of clarity.',                                         example: 'The most luminous people in the room are usually the ones who ask the best questions.' },
  { word: 'Sagacity',      pos: 'n',   pronunciation: 'suh-GAS-ih-tee',    definition: 'The ability to make good judgments based on deep understanding and experience.',                  example: 'Experience alone doesn\'t build sagacity — honest reflection does.' },
  { word: 'Resilient',     pos: 'adj', pronunciation: 'rih-ZIL-ee-unt',    definition: 'Able to recover quickly from difficulties; having elastic toughness.',                            example: 'You don\'t have to be unbreakable — you just have to be resilient enough to rebuild.' },
  { word: 'Eloquent',      pos: 'adj', pronunciation: 'EL-oh-kwunt',       definition: 'Fluent and persuasive in speech or writing; powerfully expressive.',                             example: 'Being eloquent isn\'t about fancy words — it\'s about saying the right thing clearly.' },
  { word: 'Conviction',    pos: 'n',   pronunciation: 'kun-VIK-shun',      definition: 'A firmly held belief or opinion; the feeling of being certain about something.',                 example: 'Acting with conviction means moving forward even when others doubt your path.' },
  { word: 'Deliberate',    pos: 'adj', pronunciation: 'dih-LIB-er-ut',     definition: 'Done consciously and intentionally; careful and unhurried in decision-making.',                  example: 'Deliberate practice — not just repetition — is what creates mastery.' },
  { word: 'Acumen',        pos: 'n',   pronunciation: 'AK-yoo-men',        definition: 'The ability to make good judgments and quick decisions; keenness of mind.',                      example: 'Business acumen isn\'t taught — it\'s developed through experience and attention.' },
  { word: 'Sovereignty',   pos: 'n',   pronunciation: 'SOV-rin-tee',       definition: 'Supreme power or authority; complete control over oneself or one\'s domain.',                    example: 'Personal sovereignty starts when you stop giving others power over your peace.' },
  { word: 'Paradigm',      pos: 'n',   pronunciation: 'PAIR-uh-dyme',      definition: 'A typical pattern or model; a framework shaping how you see and interpret the world.',           example: 'Shifting your paradigm often matters more than changing your tactics.' },
  { word: 'Veracity',      pos: 'n',   pronunciation: 'vuh-RAS-ih-tee',    definition: 'Habitual truthfulness; accuracy and precision in what is claimed.',                              example: 'Veracity builds trust faster than any strategy or sales pitch.' },
  { word: 'Impetus',       pos: 'n',   pronunciation: 'IM-pih-tus',        definition: 'A driving force; something that makes a process happen or happen faster.',                       example: 'Sometimes failure is the greatest impetus for your greatest leap.' },
  { word: 'Discernment',   pos: 'n',   pronunciation: 'dih-SURN-munt',     definition: 'The ability to judge well; perceptive insight into people and situations.',                      example: 'Discernment lets you know which opportunities to pursue and which to walk away from.' },
  { word: 'Calibrate',     pos: 'v',   pronunciation: 'KAL-ih-brayt',      definition: 'To adjust or fine-tune carefully based on observation and feedback.',                            example: 'High performers don\'t just execute — they constantly calibrate their approach.' },
  { word: 'Proliferate',   pos: 'v',   pronunciation: 'pruh-LIF-er-ayt',   definition: 'To grow or multiply rapidly; to spread to many places or people.',                              example: 'Small, consistent habits proliferate into your entire identity over time.' },
  { word: 'Cognizant',     pos: 'adj', pronunciation: 'KOG-nih-zunt',      definition: 'Aware of and having knowledge or understanding of something.',                                   example: 'Be cognizant of who gets your energy — not everyone deserves access to you.' },
  { word: 'Synthesis',     pos: 'n',   pronunciation: 'SIN-thuh-sis',      definition: 'The combination of ideas to form a new, coherent whole.',                                        example: 'Genius is often just synthesis — connecting things others haven\'t put together yet.' },
  { word: 'Discipline',    pos: 'n',   pronunciation: 'DIS-ih-plin',       definition: 'The ability to follow rules and control behavior; consistent practice of good habits.',          example: 'Discipline isn\'t punishment — it\'s the bridge between your goals and your results.' },
  { word: 'Ephemeral',     pos: 'adj', pronunciation: 'ih-FEM-er-ul',      definition: 'Lasting for a very short time; transitory.',                                                     example: 'Pain is ephemeral — what you build through it is permanent.' },
  { word: 'Propitious',    pos: 'adj', pronunciation: 'pruh-PISH-us',      definition: 'Giving or indicating a good chance of success; favorable.',                                      example: 'There is no propitious moment — the best time to start is always now.' },
  { word: 'Ardor',         pos: 'n',   pronunciation: 'AR-der',            definition: 'Enthusiasm and passion; intense, burning dedication to a cause or goal.',                        example: 'Without ardor, even a perfect strategy feels empty and unsustainable.' },
  { word: 'Meticulous',    pos: 'adj', pronunciation: 'muh-TIK-yoo-lus',   definition: 'Showing great attention to detail; very careful and precise.',                                  example: 'Meticulous execution of simple ideas beats careless execution of brilliant ones.' },
  { word: 'Ascend',        pos: 'v',   pronunciation: 'uh-SEND',           definition: 'To move upward; to rise to a higher level, rank, or degree.',                                   example: 'To ascend, you must first be willing to leave who you were behind.' },
  { word: 'Autonomy',      pos: 'n',   pronunciation: 'aw-TON-oh-mee',     definition: 'The right and ability to make your own decisions and govern yourself.',                         example: 'True autonomy is built, not given — it comes from proving you can lead yourself.' },
  { word: 'Candor',        pos: 'n',   pronunciation: 'KAN-der',           definition: 'The quality of being open, honest, and direct in communication.',                               example: 'Candor, delivered with care, is one of the most powerful gifts you can give someone.' },
  { word: 'Diligence',     pos: 'n',   pronunciation: 'DIL-ih-junss',      definition: 'Steady, earnest effort; careful and persistent application to one\'s work.',                    example: 'Talent gets noticed — diligence gets results.' },
  { word: 'Endurance',     pos: 'n',   pronunciation: 'en-DYOOR-unss',     definition: 'The ability to sustain effort or hardship over a long period of time.',                         example: 'Success tests your endurance more than your intelligence.' },
  { word: 'Fidelity',      pos: 'n',   pronunciation: 'fih-DEL-ih-tee',    definition: 'Faithfulness; exact correspondence to what was promised or agreed upon.',                       example: 'Fidelity to your word — especially when it\'s inconvenient — is where character lives.' },
  { word: 'Gravitas',      pos: 'n',   pronunciation: 'GRAV-ih-taas',      definition: 'Dignity and seriousness of manner; a quality of substance and weight.',                         example: 'Gravitas isn\'t performed — it\'s earned through years of showing up fully.' },
  { word: 'Heuristic',     pos: 'adj', pronunciation: 'hyoo-RIS-tik',      definition: 'Enabling discovery through experience and trial rather than fixed rules.',                      example: 'The most successful people operate on heuristic principles, not rigid playbooks.' },
  { word: 'Integrity',     pos: 'n',   pronunciation: 'in-TEG-rih-tee',    definition: 'The quality of being honest; the state of being whole and undivided in your values.',          example: 'Integrity means you act the same whether or not anyone is watching.' },
  { word: 'Judicious',     pos: 'adj', pronunciation: 'joo-DISH-us',       definition: 'Having, showing, or done with good judgment; wise and careful.',                               example: 'Judicious choices about your time compound into an extraordinary life.' },
  { word: 'Kinetic',       pos: 'adj', pronunciation: 'kih-NET-ik',        definition: 'Relating to motion; full of energy and activity.',                                               example: 'Ideas are only potential — it\'s kinetic action that changes everything.' },
  { word: 'Legacy',        pos: 'n',   pronunciation: 'LEG-uh-see',        definition: 'Something transmitted by or received from an ancestor; what you leave behind.',                 example: 'Legacy isn\'t about fame — it\'s about who you made better by being here.' },
  { word: 'Mastery',       pos: 'n',   pronunciation: 'MAS-ter-ee',        definition: 'Comprehensive knowledge or skill in a subject or accomplishment.',                              example: 'Mastery isn\'t a destination — it\'s a daily practice of showing up at your edge.' },
  { word: 'Nourish',       pos: 'v',   pronunciation: 'NUR-ish',           definition: 'To provide sustenance; to keep alive and support the growth of.',                               example: 'Nourish your mind daily — what you feed your focus determines what you build.' },
  { word: 'Optimism',      pos: 'n',   pronunciation: 'OP-tih-miz-um',     definition: 'Hopefulness and confidence about the future; a tendency to see the best.',                     example: 'Optimism isn\'t naive — it\'s a competitive advantage in uncertain times.' },
  { word: 'Perseverance',  pos: 'n',   pronunciation: 'pur-suh-VEER-unss', definition: 'Continued effort despite difficulty or delay in achieving success.',                           example: 'Most breakthroughs are just perseverance that outlasted everyone else\'s doubt.' },
  { word: 'Quintessential',pos: 'adj', pronunciation: 'kwin-tuh-SEN-shul', definition: 'Representing the most perfect or typical example of something.',                               example: 'He became the quintessential example of what consistent effort produces.' },
  { word: 'Rectitude',     pos: 'n',   pronunciation: 'REK-tih-tyood',     definition: 'Morally correct behavior; adherence to a strong ethical code.',                                example: 'Rectitude is choosing the right action even when no one would notice the wrong one.' },
  { word: 'Steadfast',     pos: 'adj', pronunciation: 'STED-fast',         definition: 'Resolutely firm and unwavering; not subject to change.',                                        example: 'Be steadfast in your vision and flexible in your methods.' },
  { word: 'Transcend',     pos: 'v',   pronunciation: 'tran-SEND',         definition: 'To go beyond the limits of; to surpass or rise above.',                                         example: 'To transcend your circumstances, you must first stop being defined by them.' },
  { word: 'Unwavering',    pos: 'adj', pronunciation: 'un-WAY-ver-ing',    definition: 'Steady and resolute; not changing or becoming weak.',                                           example: 'Unwavering belief in your path is what carries you through the years nobody notices you.' },
  { word: 'Valor',         pos: 'n',   pronunciation: 'VAL-er',            definition: 'Great courage in the face of danger; strength of character under pressure.',                    example: 'Valor isn\'t the absence of fear — it\'s choosing action despite it.' },
  { word: 'Wisdom',        pos: 'n',   pronunciation: 'WIZ-dum',           definition: 'The ability to make sensible decisions from experience and good judgment.',                     example: 'Wisdom is what turns years of experience into clarity you can actually use.' },
  { word: 'Xenial',        pos: 'adj', pronunciation: 'ZEE-nee-ul',        definition: 'Friendly to strangers; hospitable and generous in spirit.',                                     example: 'A xenial spirit opens doors that talent alone never could.' },
  { word: 'Yield',         pos: 'v',   pronunciation: 'YEELD',             definition: 'To produce or provide; to give way in order to allow something greater.',                       example: 'Sometimes you have to yield on the small things to win on what truly matters.' },
  { word: 'Zeal',          pos: 'n',   pronunciation: 'ZEEL',              definition: 'Great energy and enthusiasm in pursuit of a cause or objective.',                               example: 'Sustainable zeal comes from purpose — not pressure.' },
  { word: 'Alacrity',      pos: 'n',   pronunciation: 'uh-LAK-rih-tee',    definition: 'Brisk and cheerful readiness; eager willingness to act.',                                      example: 'She approached every challenge with alacrity — that energy was contagious.' },
  { word: 'Brevity',       pos: 'n',   pronunciation: 'BREV-ih-tee',       definition: 'Concise and exact use of words; shortness of time.',                                           example: 'Brevity in communication is a form of respect — and a sign of clear thinking.' },
  { word: 'Clarity',       pos: 'n',   pronunciation: 'KLAIR-ih-tee',      definition: 'The quality of being clear, coherent, and easily understood.',                                 example: 'Clarity on what you want is the beginning of actually getting it.' },
  { word: 'Dexterity',     pos: 'n',   pronunciation: 'dek-STER-ih-tee',   definition: 'Skill in performing tasks, especially with the hands or mind.',                                example: 'Mental dexterity — the ability to shift thinking quickly — is an underrated superpower.' },
  { word: 'Efficacious',   pos: 'adj', pronunciation: 'ef-ih-KAY-shus',    definition: 'Effective; producing the intended or desired result.',                                          example: 'The most efficacious action is often the simplest one done with full commitment.' },
  { word: 'Fervent',       pos: 'adj', pronunciation: 'FUR-vunt',          definition: 'Having or showing great warmth and intensity of feeling.',                                     example: 'Fervent belief in what you\'re building is fuel that logic alone can\'t provide.' },
  { word: 'Grit',          pos: 'n',   pronunciation: 'GRIT',              definition: 'Courage and resolve; unyielding strength of character.',                                        example: 'Grit is the one trait that predicts success more than talent or IQ.' },
  { word: 'Humility',      pos: 'n',   pronunciation: 'hyoo-MIL-ih-tee',   definition: 'A modest view of one\'s own importance; openness to learning.',                               example: 'Humility is not thinking less of yourself — it\'s thinking of yourself less.' },
  { word: 'Ingenuity',     pos: 'n',   pronunciation: 'in-juh-NOO-ih-tee', definition: 'The quality of being clever, original, and inventive.',                                        example: 'Ingenuity isn\'t about resources — it\'s about resourcefulness.' },
  { word: 'Juncture',      pos: 'n',   pronunciation: 'JUNK-cher',         definition: 'A critical point in time; a place where things meet or connect.',                              example: 'Every juncture is a chance to choose who you\'re becoming next.' },
  { word: 'Keen',          pos: 'adj', pronunciation: 'KEEN',              definition: 'Having a sharp edge or point; eagerly interested; intellectually sharp.',                      example: 'A keen mind doesn\'t just absorb information — it asks better questions.' },
  { word: 'Lucid',         pos: 'adj', pronunciation: 'LOO-sid',           definition: 'Expressed clearly; easy to understand; mentally clear.',                                        example: 'Lucid thinking under pressure is what separates leaders from passengers.' },
  { word: 'Momentum',      pos: 'n',   pronunciation: 'moh-MEN-tum',       definition: 'The force gained by motion; the drive that builds as you continue moving forward.',           example: 'Momentum is fragile at first — protect it by showing up every day.' },
]

export function getTodayWod(): WodEntry {
  const now   = new Date()
  const start = new Date(now.getFullYear(), 0, 0)
  const diff  = now.getTime() - start.getTime()
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24))
  return WORDS[dayOfYear % WORDS.length]
}
